FROM arm64v8/ubuntu

ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-arm64 /tini
RUN chmod +x /tini

ADD epic-node/target/release/arm64/epic-node /usr/local/bin/epic-node
RUN chmod +x /usr/local/bin/epic-node
ADD docker_entrypoint.sh /usr/local/bin/docker_entrypoint.sh
RUN chmod a+x /usr/local/bin/docker_entrypoint.sh
ADD foundation.json /epic/foundation.json
ADD epic-server.toml /epic/epic-server.toml

